'use client'
import { Header } from '@/components/header'
import '../styles/globals.css'
import { SessionProvider } from "next-auth/react"
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tarefas+',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <SessionProvider>
          <Header/>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
